### ISSUE TITLE
first name and last name search

### ISSUE THREAD

**Issue by robot-athletics** [betrailrun/beath-track#11]
When searching on the firstname and lastname, the search returns an entry.
When clicking on this entry, the page does not show.
 Report by Renauld Secretaire renauld.chapellier@diplomats.com 
 {"version":"0.0.0","name":"beathletics","buildDate":"\"2022-03-29T16:19:59.174Z\"","VERSION":"10c4c06","COMMITHASH":"10c4c063394be7ad83ea73e7ea200899ec041aec","BRANCH":"uat","LASTCOMMITDATETIME":"2022-03-29T18:13:46+02:00"}

**Comment by fwauters** [comment]
`core.mjs:6485 ERROR Error: The requested path contains undefined segment at index 1
    at validateCommands (router.mjs:4968:19)
    at Router.navigate (router.mjs:4755:9)
    at PublicSearchBarComponent.onSearchSelect (public-search-bar.component.ts:59:19)
    at PublicSearchBarComponent_ng_container_8_ng_container_1_ng_container_2_mat_option_1_Template_mat_option_click_0_listener (public-search-bar.component.html:44:22)
    at executeListenerWithErrorHandling (core.mjs:14979:1)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:15023:1)
    at HTMLElement.<anonymous> (platform-browser.mjs:466:38)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25535:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)`
